ALTER TABLE articles MODIFY created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE articles ADD enabled BOOLEAN DEFAULT 1;
ALTER TABLE device ADD time_created DATETIME;
UPDATE device SET time_created='0000-00-00 00:00:00';
ALTER TABLE device MODIFY time_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE device MODIFY device_name VARCHAR(255) NOT NULL;
ALTER TABLE full_device_name VARCHAR(255) NOT NULL;


